<ul class="alignwide wp-block-post-template is-layout-flow">

   <li class="wp-block-post post-827 blog type-blog status-publish format-standard has-post-thumbnail hentry category-category1 tag-budget tag-food tag-lorem tag-lorem-ipsum tag-retaill tag-sale">
      <div class="wp-block-group gap-0 bw-image is-vertical is-layout-flex wp-container-28">
         <figure style="margin-top:calc(1.75 * var(--wp--style--block-gap));" class="alignwide wp-block-post-featured-image"><a href="https://wealthapp.dotncube.in/blog/lorem-ipsum-is-simply-dummy-text-of-the-printing-8/" target="_self"><img width="565" height="289" src="https://wealthapp.dotncube.in/wp-content/uploads/2023/06/blog-listing-img-2.webp" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Lorem Ipsum is simply dummy text of the printing" decoding="async" srcset="https://wealthapp.dotncube.in/wp-content/uploads/2023/06/blog-listing-img-2.webp 565w, https://wealthapp.dotncube.in/wp-content/uploads/2023/06/blog-listing-img-2-300x153.webp 300w" sizes="(max-width: 565px) 100vw, 565px"></a></figure>
         <h2 class="alignwide blog-post-title wp-block-post-title has-var-wp-custom-typography-font-size-huge-clamp-2-25-rem-4-vw-2-75-rem-font-size"><a href="https://wealthapp.dotncube.in/blog/lorem-ipsum-is-simply-dummy-text-of-the-printing-8/" target="_self">Lorem Ipsum is simply dummy text of the printing</a></h2>
         <div class="blog-post-shorttext wp-block-post-excerpt">
            <p class="wp-block-post-excerpt__excerpt">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book </p>
         </div>
         <div class="wp-block-group full-width is-content-justification-right is-nowrap is-layout-flex wp-container-27" style="margin-top:0"><a class="txt-inline-img-l  explore-text  wp-block-read-more" href="https://wealthapp.dotncube.in/blog/lorem-ipsum-is-simply-dummy-text-of-the-printing-8/" target="_self">Read More <img decoding="async" width="24" height="24" class="wp-image-39" style="width: 24px" src="https://wealthapp.dotncube.in/wp-content/uploads/2023/03/cta-arrow.png" alt=""><span class="screen-reader-text">: Lorem Ipsum is simply dummy text of the printing</span></a></div>
      </div>
   </li>
   
   <li class="wp-block-post post-826 blog type-blog status-publish format-standard has-post-thumbnail hentry">
      <div class="wp-block-group gap-0 bw-image is-vertical is-layout-flex wp-container-30">
         <figure style="margin-top:calc(1.75 * var(--wp--style--block-gap));" class="alignwide wp-block-post-featured-image"><a href="https://wealthapp.dotncube.in/blog/lorem-ipsum-is-simply-dummy-text-of-the-printing-7/" target="_self"><img width="565" height="289" src="https://wealthapp.dotncube.in/wp-content/uploads/2023/06/blog-listing-img-3.webp" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Lorem Ipsum is simply dummy text of the printing" decoding="async" loading="lazy" srcset="https://wealthapp.dotncube.in/wp-content/uploads/2023/06/blog-listing-img-3.webp 565w, https://wealthapp.dotncube.in/wp-content/uploads/2023/06/blog-listing-img-3-300x153.webp 300w" sizes="(max-width: 565px) 100vw, 565px"></a></figure>
         <h2 class="alignwide blog-post-title wp-block-post-title has-var-wp-custom-typography-font-size-huge-clamp-2-25-rem-4-vw-2-75-rem-font-size"><a href="https://wealthapp.dotncube.in/blog/lorem-ipsum-is-simply-dummy-text-of-the-printing-7/" target="_self">Lorem Ipsum is simply dummy text of the printing</a></h2>
         <div class="blog-post-shorttext wp-block-post-excerpt">
            <p class="wp-block-post-excerpt__excerpt">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
         </div>
         <div class="wp-block-group full-width is-content-justification-right is-nowrap is-layout-flex wp-container-29" style="margin-top:0"><a class="txt-inline-img-l  explore-text  wp-block-read-more" href="https://wealthapp.dotncube.in/blog/lorem-ipsum-is-simply-dummy-text-of-the-printing-7/" target="_self">Read More <img decoding="async" width="24" height="24" class="wp-image-39" style="width: 24px" src="https://wealthapp.dotncube.in/wp-content/uploads/2023/03/cta-arrow.png" alt=""><span class="screen-reader-text">: Lorem Ipsum is simply dummy text of the printing</span></a></div>
      </div>
   </li>
   <li class="wp-block-post post-825 blog type-blog status-publish format-standard has-post-thumbnail hentry">
      <div class="wp-block-group gap-0 bw-image is-vertical is-layout-flex wp-container-32">
         <figure style="margin-top:calc(1.75 * var(--wp--style--block-gap));" class="alignwide wp-block-post-featured-image"><a href="https://wealthapp.dotncube.in/blog/lorem-ipsum-is-simply-dummy-text-of-the-printing-6/" target="_self"><img width="565" height="289" src="https://wealthapp.dotncube.in/wp-content/uploads/2023/06/older-blog-img2.webp" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Lorem Ipsum is simply dummy text of the printing" decoding="async" loading="lazy" srcset="https://wealthapp.dotncube.in/wp-content/uploads/2023/06/older-blog-img2.webp 565w, https://wealthapp.dotncube.in/wp-content/uploads/2023/06/older-blog-img2-300x153.webp 300w" sizes="(max-width: 565px) 100vw, 565px"></a></figure>
         <h2 class="alignwide blog-post-title wp-block-post-title has-var-wp-custom-typography-font-size-huge-clamp-2-25-rem-4-vw-2-75-rem-font-size"><a href="https://wealthapp.dotncube.in/blog/lorem-ipsum-is-simply-dummy-text-of-the-printing-6/" target="_self">Lorem Ipsum is simply dummy text of the printing</a></h2>
         <div class="blog-post-shorttext wp-block-post-excerpt">
            <p class="wp-block-post-excerpt__excerpt">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
         </div>
         <div class="wp-block-group full-width is-content-justification-right is-nowrap is-layout-flex wp-container-31" style="margin-top:0"><a class="txt-inline-img-l  explore-text  wp-block-read-more" href="https://wealthapp.dotncube.in/blog/lorem-ipsum-is-simply-dummy-text-of-the-printing-6/" target="_self">Read More <img decoding="async" width="24" height="24" class="wp-image-39" style="width: 24px" src="https://wealthapp.dotncube.in/wp-content/uploads/2023/03/cta-arrow.png" alt=""><span class="screen-reader-text">: Lorem Ipsum is simply dummy text of the printing</span></a></div>
      </div>
   </li>
</ul>